name: correbirras
description: "Agenda de carreras Correbirras"
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  html: ^0.15.4
  url_launcher: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.10+1
  share_plus: ^9.0.0
  upgrader: ^10.3.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
