name: Correbirras
description: "Agenda de carreras Correbirras"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path_provider: ^2.1.3
  html: ^0.15.4
  url_launcher: ^6.0.0

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
