// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABC123DEF456GHI789JKL012MNO345PQR',
    appId: '1:123456789:web:abc123def456ghi789',
    messagingSenderId: '123456789',
    projectId: 'correbirras',
    authDomain: 'correbirras.firebaseapp.com',
    storageBucket: 'correbirras.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_aQQHIs2RD4wIDawXli9g8fcfjo_h1E',
    appId: '1:1053599538056:android:e7043176b4851373faf83d',
    messagingSenderId: '1053599538056',
    projectId: 'appcorrebirras',
    storageBucket: 'appcorrebirras.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABC123DEF456GHI789JKL012MNO345PQR',
    appId: '1:123456789:ios:abc123def456ghi789',
    messagingSenderId: '123456789',
    projectId: 'correbirras',
    storageBucket: 'correbirras.appspot.com',
    iosBundleId: 'com.correbirras.agenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABC123DEF456GHI789JKL012MNO345PQR',
    appId: '1:123456789:macos:abc123def456ghi789',
    messagingSenderId: '123456789',
    projectId: 'correbirras',
    storageBucket: 'correbirras.appspot.com',
    iosBundleId: 'com.correbirras.agenda',
  );
}
